name       : gnome-autoar
version    : 0.1.1
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-autoar/0.1/gnome-autoar-0.1.1.tar.xz : f65cb810b562dc038ced739fbf59739fd5df1a8e848636e21f363ded9f349ac9
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : Automatic archive library
description: |
    Automatic archives creating and extracting library 
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
