name       : gnome-autoar
version    : 0.2.2
release    : 3
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-autoar/0.2/gnome-autoar-0.2.2.tar.xz : e1fe2c06eed30305c38bf0939c72b0e51b4716658e2663a0cf4a4bf57874ca62
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : Automatic archive library
description: |
    Automatic archives creating and extracting library
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
