name       : gnome-autoar
version    : 0.2.4
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-autoar/0.2/gnome-autoar-0.2.4.tar.xz : 0a34c377f8841abbf4c29bc848b301fbd8e4e20c03d7318c777c58432033657a
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : Automatic archive library
description: |
    Automatic archives creating and extracting library
builddeps  :
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
