name       : gnome-autoar
version    : 0.4.0
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-autoar/0.4/gnome-autoar-0.4.0.tar.xz : ea8c6d524babc712ac59e1d0e3ac8bf0137482dadf33c94fe9113794a1bc4474
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : Automatic archive library
description: |
    Automatic archives creating and extracting library
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
