name       : gnome-autoar
version    : 0.3.0
release    : 10
source     :
    - https://download.gnome.org/sources/gnome-autoar/0.3/gnome-autoar-0.3.0.tar.xz : f2c112c0120cca2bf5a82c5b0ac8cba90ce10d21fec78f50a3bc513fdd64586b
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : Automatic archive library
description: |
    Automatic archives creating and extracting library
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
