name       : gnome-autoar
version    : 0.3.1
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-autoar/0.3/gnome-autoar-0.3.1.tar.xz : 0e78713e6f0de339fdee16bab82753ae290fe80fa7b4ba6e3db8c1465b81d0f8
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : Automatic archive library
description: |
    Automatic archives creating and extracting library
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libarchive)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
